"""
Django settings for blog project.

Generated by 'django-admin startproject' using Django 1.9.

For more information on this file, see
https://docs.djangoproject.com/en/1.9/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.9/ref/settings/
"""

import os
import sys

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.9/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'wn+jkjwujb!rg3vh)m(p1+p%a82k7%ca%+-044=88@=ea9d87d'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['127.0.0.1', 'localhost', '118.25.126.182']

# 引入APPS目录  install_apps就能直接引入我们的功能模块
sys.path.insert(0, BASE_DIR)
sys.path.insert(0, os.path.join(BASE_DIR, 'APPS'))
sys.path.insert(0, os.path.join(BASE_DIR, 'utils'))
# ALLOWED_HOSTS = ['*']

# Application definition

INSTALLED_APPS = [
    'monitor',
    'mdeditor',
    'blog_app',
    'utils',
    'django_crontab',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

]

MIDDLEWARE_CLASSES = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'middleware.blog_middleware.UserBasedExceptionMiddleware',
    'middleware.blog_middleware.ResponseDataMiddleware',
]
CORS_ORIGIN_ALLOW_ALL = True

ROOT_URLCONF = 'blog.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'template')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'APPS.blog_app.views.base_context',
            ],
        },
    },
]

WSGI_APPLICATION = 'blog.wsgi.application'

# Database
# https://docs.djangoproject.com/en/1.9/ref/settings/#databases

from utils.config import Config

DBinfo = Config.DBConfig

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': DBinfo.MYSQL_DANAME,
        'USER': DBinfo.MYSQL_USER,
        'PASSWORD': DBinfo.MYSQL_PASSWD,
        'HOST': DBinfo.MYSQL_HOST,
        'PORT': DBinfo.MYSQL_PORT,
    },
}

# Password validation
# https://docs.djangoproject.com/en/1.9/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/1.9/topics/i18n/
LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = False
# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.9/howto/static-files/

AUTH_USER_MODEL = 'blog_app.UserProfile'
STATIC_URL = '/static/'
STATIC_ROOT = 'web_static'

STATICFILES_DIRS = (
    os.path.join(BASE_DIR, 'static/'),
)
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# 登录success跳转
LOGIN_REDIRECT_URL = '/'
# ---------------------------------------------
#              定时任务 django-crontab
# 定时任务 监控服务器资源
# python manage.py crontab add    添加定时任务
#                        ~ remove 删除定时任务
#                        ~ show   查看定时任务
CRONJOBS = [
    ('*/1 * * * *', 'utils.monitor_mem.run', '>> /home/horsun/Desktop/error.log'),
    ('*/1 * * * *', 'utils.monitor_network.run', '>> /home/horsun/Desktop/error.log'),
]
# CRONTAB_COMMAND_SUFFIX = '2>&1'
# 注意包与包之间的关系
# ---------------------------------------------

# -----------------------------
#        定时任务 django-celery   /还在尝试
# -----------------------------
# BROKER_URL = 'django://localhost:8000//'
# CELERYBEAT_SCHEDULER = 'djcelery.schedulers.DatabaseScheduler'
# CELERY_TIMEZONE = 'Asia/Shanghai'
